// Module: tg1
// Type: U
// Lines: 128062-128080
//
var tg1 = U((MdQ)=>{
    Object.defineProperty(MdQ, "__esModule", {
        value: !0
    });
    MdQ.BAGGAGE_MAX_TOTAL_LENGTH = MdQ.BAGGAGE_MAX_PER_NAME_VALUE_PAIRS = MdQ.BAGGAGE_MAX_NAME_VALUE_PAIRS = MdQ.BAGGAGE_HEADER = MdQ.BAGGAGE_ITEMS_SEPARATOR = MdQ.BAGGAGE_PROPERTIES_SEPARATOR = MdQ.BAGGAGE_KEY_PAIR_SEPARATOR = void 0;
    MdQ.BAGGAGE_KEY_PAIR_SEPARATOR = "=";
    MdQ.BAGGAGE_PROPERTIES_SEPARATOR = ";";
    MdQ.BAGGAGE_ITEMS_SEPARATOR = ",";
    MdQ.BAGGAGE_HEADER = "baggage";
    MdQ.BAGGAGE_MAX_NAME_VALUE_PAIRS = 180;
    MdQ.BAGGAGE_MAX_PER_NAME_VALUE_PAIRS = 4096;
    MdQ.BAGGAGE_MAX_TOTAL_LENGTH = 8192;
});
